package daily.easy;

public class FindTheDifference {
    /**
     * You are given two strings s and t.
     * <p>
     * String t is generated by random shuffling string s and then add one more letter at a random position.
     * <p>
     * Return the letter that was added to t.
     *
     * @param s first string
     * @param t randomly generated from string s and then add more letter at a random position.
     * @return the added letter.
     */
    public char findTheDifference(String s, String t) {
        char c = 0;
        for (char cs : s.toCharArray()) c ^= cs;
        for (char ct : t.toCharArray()) c ^= ct;
        return c;
    }

    public char findTheDifference0(String s, String t) {
        char diffChar = ' ';
        int[] letters = occurrences(s);
        int[] lettert = occurrences(t);

        for (int i = 0; i < 26; i++) {
            if (letters[i] != lettert[i]) {
                diffChar = (char) (i + 'a');
                break;
            }
        }

        return diffChar;
    }

    private static int[] occurrences(String s) {
        int[] letters = new int[26];

        for (int i = 0; i < s.length(); i++) {
            letters[s.charAt(i) - 'a']++;
        }
        return letters;
    }
}
